mod guess_the_number;
mod mutate;
mod data_types;
mod functions;
mod flow_control;
mod ownership;
mod references_and_borrowing;
mod slices;
mod use_struct;
mod example_struct;
mod defining_enum;
mod match_flow_control;
mod defining_modules;
mod using_defined_modules;
mod logger;
mod example_collections;
mod strings;
mod hash_maps;
mod errors_with_panic;
mod errors_with_result;
mod panic_or_not_panic;

fn main() {
    logger::info(&format!("Hello, {}!", "world"));
    guess_the_number::guess_the_number();
    mutate::mutate();
    data_types::data_types();
    functions::all();
    flow_control::flow_control();
    ownership::ownership();
    references_and_borrowing::references_and_borrowing();
    slices::slices();
    use_struct::use_struct();
    example_struct::example_struct();
    defining_enum::defining_enum();
    match_flow_control::match_flow_control();
    defining_modules::defining_modules();
    using_defined_modules::using_defined_modules();
    example_collections::example_collections();
    strings::strings();
    hash_maps::hash_maps();
    errors_with_panic::errors_with_panic();
    errors_with_result::errors_with_result();
    panic_or_not_panic::panic_or_not_panic();
    logger::info("Good bye!");
}
